#ifndef __morph_gpu_h
#define __morph_gpu_h
/*header generated by SPAP, may be automatically overwritten*/

#ifndef __VECTOR_TYPES_H__
#ifndef __ITYPE_DEFINED_float2
#define __ITYPE_DEFINED_float2 1
typedef struct{
	float x;
	float y;
}float2;
#endif
#endif
#ifndef __ITYPE_DEFINED_FLine
#define __ITYPE_DEFINED_FLine 1
typedef struct{
	float2 P;
	float2 Q;
	float2 vec;
	float2 unit_perpendicular;
	float length;char __ipad_04ef7ba4[4];
}FLine;
#endif
#ifdef __cplusplus
extern "C"{
#endif
#ifndef _MORPH_GPU_INITED
#define _MORPH_GPU_INITED
int _init2945411250e9b5a762dbaa504d2bcaec(); static int __cpp__init2945411250e9b5a762dbaa504d2bcaec=_init2945411250e9b5a762dbaa504d2bcaec();
#endif
extern void __cdecl warp_bsgp(unsigned char *Isrc_cpu,unsigned char *Idst_cpu,int w,int h,int bytes,int bytes_line,FLine *lines_src_cpu,FLine *lines_dst_cpu,int lines_num,float a,float b,float p);
extern void __cdecl cross_dissolve_bsgp(unsigned char *I0_cpu,unsigned char *I1_cpu,int bytes,float s,unsigned char *Idst_cpu);
extern void __cdecl backward_imtransform_bsgp(unsigned char *I0_cpu,int w,int h,int bytes,int bytes_line,double *mat);
#ifdef __cplusplus
}
#endif
#endif
